# Generated by Django 2.2.6 on 2020-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='descriptions',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='documents',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
