# Generated by Django 2.2.6 on 2020-05-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('IT', 'Information Technologies'), ('Bussiness Managment', 'Bussiness Managment'), ('Digital Marketing', 'Digital Marketing'), ('Computer Science', 'Computer Science'), ('Civil Engineering', 'Civil Engineering'), ('AI', 'Artificial & Inteligence'), ('Other', 'Other')], max_length=120),
        ),
        migrations.AlterField(
            model_name='education',
            name='ended_at',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='profession',
            field=models.CharField(choices=[('Student or Learning', 'Student or Learning'), ('Instructor or Teacher', 'Instructor or Teacher'), ('Other', 'Other')], default=1, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(choices=[('Student or Learning', 'Student or Learning'), ('Instructor or Teacher', 'Instructor or Teacher'), ('Other', 'Other')], default='Web Developer', max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(max_length=300),
        ),
    ]
