# Generated by Django 2.2.6 on 2020-06-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200530_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('IT', 'Information Technologies'), ('Bussiness Managment', 'Bussiness Managment'), ('Digital Marketing', 'Digital Marketing'), ('Computer Science', 'Computer Science'), ('Civil Engineering', 'Civil Engineering'), ('AI', 'Artificial & Inteligence'), ('Other', 'Other')], default=1, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
