# Generated by Django 2.2.6 on 2020-06-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200602_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='company',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='is_currently_working',
            new_name='is_currently_teacher',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='education',
            name='bio',
            field=models.TextField(blank=True, default='Hello buddies..!'),
        ),
        migrations.AddField(
            model_name='experience',
            name='research',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
